name: Case Study Submission
description: Submit a project for live review or as a case study for the Blueprint.
title: "Case Study: [Project Title or Anonymized Label]"
labels: ["type:case-study", "status:triage"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: One-paragraph summary (domain, goals, constraints).
  - type: textarea
    id: architecture
    attributes:
      label: Architecture Overview
      description: Describe core components (attach a diagram link if possible).
  - type: textarea
    id: decision
    attributes:
      label: Key Architectural Decision
      description: One important trade-off or decision made.
  - type: textarea
    id: challenges
    attributes:
      label: Hardest Challenge
      description: What you’d like the community to focus on.
    validations:
      required: true
  - type: checkboxes
    id: confidentiality
    attributes:
      label: Confidentiality
      options:
        - label: Safe to publish as-is
        - label: Needs anonymization before publishing
