name: Auto Label
on:
  issues:
    types: [opened, edited]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
