name: Auto Label Issues
on:
  issues:
    types: [opened, edited, reopened]
permissions:
  contents: read
  issues: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/issue-labeler@v3.3
        with:
          configuration-path: .github/labeler.yml
          not-before: 2020-01-01
          sync-labels: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
