name: Issue Triage
on:
  issues:
    types: [opened]
permissions:
  issues: write
  repository-projects: write
jobs:
  triage:
    runs-on: ubuntu-latest
    env:
      PROJECT_URL: ${{ secrets.PROJECT_URL }}  # bind once
    steps:
      - name: Add status:triage label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: status:triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add issue to Project
        if: ${{ env.PROJECT_URL != '' }}        # check env, not secrets
        uses: actions/add-to-project@v0.6.1
        with:
          project-url: ${{ env.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
