name: PR Lint (Require Linked Issue)
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
permissions:
  pull-requests: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Require "Closes #<num>" in PR body
        uses: mszostok/action-required-labels@v5
        if: ${{ false }} # placeholder step—using a custom script below
      - name: Validate PR body contains linked issue
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const ok = /(?:close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+/i.test(body);
            if (!ok) {
              core.setFailed('PR must reference an Issue using "Closes #<issue_number>".');
            }
