name: Close Stale Issues
on:
  schedule:
    - cron: "0 3 * * 1"  # Mondays 03:00 UTC
permissions:
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 45
          days-before-close: 14
          exempt-issue-labels: "type:rfc,status:ready-for-pr,status:in-progress,priority:high"
          stale-issue-label: "status:stale"
          stale-issue-message: "Marking as stale due to inactivity. Comment to keep open."
          close-issue-message: "Closing due to inactivity. Reopen if still relevant."
